(function () {
    var scenemanager = caph.wui.widget.SceneManager.getInstance();

    scenemanager.addSceneEventHandler("scene1", {
        onCreate: function (context) {
            this.super(context);

            /*
             *
             * TODO: The codes to be generated by UI builder need to be put here.
             *
             */
            
        }
    });
}());